name: Documentation

on:
  push:
    branches: [main]
    paths:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      
      - name: Create basic mkdocs config if missing
        run: |
          if [ ! -f "mkdocs.yml" ]; then
            echo "Creating basic mkdocs.yml"
            cat > mkdocs.yml << EOF
          site_name: GenAI Pipeline Documentation
          site_description: ARM64 Optimized GenAI Pipeline on AWS
          
          nav:
            - Home: README.md
            - Security: SECURITY.md
          
          theme:
            name: material
            palette:
              primary: blue
              accent: orange
          
          markdown_extensions:
            - admonition
            - codehilite
            - toc:
                permalink: true
          EOF
          fi
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material
      
      - name: Build documentation
        run: mkdocs build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          force_orphan: true